#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(tibble)
library(magrittr)
library(dplyr)
library(XML)
library(DT)
# library(shinyWidgets)
# library(shinyjs)

outputDir <- "journals"

loadData <- function() {
  # Read all the files into a list
  files <- list.files(outputDir, full.names = TRUE)
  data <- lapply(files, read.csv, stringsAsFactors = FALSE)
  # Concatenate all data together into one data.frame
  data <- do.call(rbind, data)
  return(data)
}

db <- loadData()

generate_opml <- function(db) {
  db_name <- "journal-rss"

  opml <- xmlTree()
  # xml$addComment("OPML generated by RSS Journal")
  opml$addTag("opml", close=FALSE, attrs=c(version="1.1"))
  opml$addTag("head", close=FALSE)
  opml$addTag("title", paste0(db_name, ".opml"))
  opml$closeTag()

  opml$addTag("body", close=FALSE)
  opml$addTag(
    "outline",
    close=FALSE,
    attrs = c(
      text="RSS Journals",
      title="RSS Journals"
      )
    )
  for (i in 1:nrow(db)){
    opml$addTag(
      "outline",
      close=FALSE,
      attrs = c(
        text = db[[i, 'journal']],
        title = db[[i, 'journal']],
        description = "",
        type = "rss",
        version="RSS",
        htmlUrl = db[[i, 'html_url']],
        xmlUrl = db[[i, 'xml_url']]
      )
    )
    opml$closeTag()
  }
  opml$closeTag() # Folder
  opml$closeTag() # body
  opml$closeTag() # OPML
  return(opml)
}


# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("Journal RSS"),

    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
            downloadButton('downloadOPML', 'Download as OPML'),
            downloadButton('downloadCSV', 'Download as CSV')
        ),

        # Show a plot of the generated distribution
        mainPanel(
          dataTableOutput('table')
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

  output$table <- renderDataTable({
    db %>%
      select(journal) %>%
      DT::datatable() %>%
      formatStyle("journal", "white-space" = "nowrap")
  })

  output$downloadCSV <- downloadHandler(
    filename = function() {
      paste('journal-rss-', Sys.Date(), '.csv', sep='')
    },
    content = function(con) {
      write.csv(db, con)
    }
  )

  output$downloadOPML <- downloadHandler(
    filename = function() {
      paste('journal-rss-', Sys.Date(), '.opml', sep='')
    },
    content = function(con) {
      opml <- generate_opml(db)
      cat(saveXML(opml), file = con)
    }
  )

}

# Run the application
shinyApp(ui = ui, server = server)
