outputDir <- "journals"

loadData <- function() {
  # Read all the files into a list
  files <- list.files(outputDir, full.names = TRUE)
  data <- lapply(files, read.csv, stringsAsFactors = FALSE)
  # Concatenate all data together into one data.frame
  data <- do.call(rbind, data)
  return(data)
}

db <- loadData()

generate_opml <- function(db) {
  db_name <- "journal-rss"

  opml <- xmlTree()
  # xml$addComment("OPML generated by RSS Journal")
  opml$addTag("opml", close=FALSE, attrs=c(version="1.1"))
  opml$addTag("head", close=FALSE)
  opml$addTag("title", paste0(db_name, ".opml"))
  opml$closeTag()

  opml$addTag("body", close=FALSE)
  opml$addTag(
    "outline",
    close=FALSE,
    attrs = c(
      text="RSS Journals",
      title="RSS Journals"
    )
  )
  for (i in 1:nrow(db)){
    opml$addTag(
      "outline",
      close=FALSE,
      attrs = c(
        text = db[[i, 'journal']],
        title = db[[i, 'journal']],
        description = "",
        type = "rss",
        version="RSS",
        htmlUrl = db[[i, 'html_url']],
        xmlUrl = db[[i, 'xml_url']]
      )
    )
    opml$closeTag()
  }
  opml$closeTag() # Folder
  opml$closeTag() # body
  opml$closeTag() # OPML
  return(opml)
}

xml2tibble <- function(filepath) {
  opml_parsed <- XML::xmlTreeParse(filepath, useInternalNode=TRUE)
  nodes_of_interest <- XML::getNodeSet(opml_parsed, '//body/outline')
  opml_as_tibble <- data.table::rbindlist(
    lapply(nodes_of_interest, function(x) {
      data.frame(t(XML::xpathSApply(x, ".//outline", xmlAttrs)))
      }),
    fill=TRUE
    ) %>%
    as_tibble()
  return(opml_as_tibble)
}

